server:
  name: go-posgresql-tutorial
  port: 8080
template: true

sql:
  driver: postgres
  data_source_name: host=localhost port=5432 user=postgres dbname=masterdata2 sslmode=disable password=abcd1234
log:
  level: info
  duration: duration
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: body
  response: response
  size: size
