server:
  name: go-sql-rest-api
  port: 8080

sql:
  driver: postgres
  data_source_name: user=postgres password=postgres dbname=masterdata sslmode=disable
log:
  level: info
  duration: duration
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: body
  response: response
  size: size
